//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartClass.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You already confirmed your email address!.
        /// </summary>
        public static string AlreadyComfirmEmail {
            get {
                return ResourceManager.GetString("AlreadyComfirmEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attachment not found.
        /// </summary>
        public static string AttachmentNotFound {
            get {
                return ResourceManager.GetString("AttachmentNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bad sprint value.
        /// </summary>
        public static string BadSprintValue {
            get {
                return ResourceManager.GetString("BadSprintValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You cannot accept this invite.
        /// </summary>
        public static string CannotAcceptInvite {
            get {
                return ResourceManager.GetString("CannotAcceptInvite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You cannot deny this invite.
        /// </summary>
        public static string CannotDenyInvite {
            get {
                return ResourceManager.GetString("CannotDenyInvite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can not get content type of file.
        /// </summary>
        public static string CannotGetFileContentType {
            get {
                return ResourceManager.GetString("CannotGetFileContentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot save the file.
        /// </summary>
        public static string CannotSaveFile
        {
            get
            {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        public static string ProjectNotFound
        {
            get
            {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        public static string IncorectBankCard
        {
            get
            {
                return ResourceManager.GetString("IncorectBankCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment not found.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data has been modified by another user.
        /// </summary>
        public static string ConcurrencyCheck {
            get {
                return ResourceManager.GetString("ConcurrencyCheck", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong code or this code is deprecated, try again!.
        /// </summary>
        public static string ConfirmEmailInvalidCode {
            get {
                return ResourceManager.GetString("ConfirmEmailInvalidCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First you need to confirm your email address.
        /// </summary>
        public static string EmailNotConfirm {
            get {
                return ResourceManager.GetString("EmailNotConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ThisEvent doesn&apos;t found.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file is empty.
        /// </summary>
        public static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File with this name already exist.
        /// </summary>
        public static string FileNameAlreadyExist {
            get {
                return ResourceManager.GetString("FileNameAlreadyExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        public static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalide Code.
        /// </summary>
        public static string Invalid2FVCode {
            get {
                return ResourceManager.GetString("Invalid2FVCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid 2-step verification provider.
        /// </summary>
        public static string Invalid2StepVerification {
            get {
                return ResourceManager.GetString("Invalid2StepVerification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Due date should be not in the past.
        /// </summary>
        public static string InvalidDateOfEnd {
            get {
                return ResourceManager.GetString("InvalidDateOfEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File must be image.
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Story points most be greater than 0 and less 100.
        /// </summary>
        public static string InvalidStoryPoints {
            get {
                return ResourceManager.GetString("InvalidStoryPoints", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid refrash token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid token verification.
        /// </summary>
        public static string InvalidTokenVerification {
            get {
                return ResourceManager.GetString("InvalidTokenVerification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have already confirmed this invitation.
        /// </summary>
        public static string InviteAlreadyAccerted {
            get {
                return ResourceManager.GetString("InviteAlreadyAccerted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This invite not found or it already answered.
        /// </summary>
        public static string InviteNotFound {
            get {
                return ResourceManager.GetString("InviteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don`t have permissions.
        /// </summary>
        public static string NotPermission {
            get {
                return ResourceManager.GetString("NotPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only creator of the task can assign another users.
        /// </summary>
        public static string NotPermissionAssignUser {
            get {
                return ResourceManager.GetString("NotPermissionAssignUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only cretor or workspace owner can delete comments.
        /// </summary>
        public static string NotPermissionDeleteComment {
            get {
                return ResourceManager.GetString("NotPermissionDeleteComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only creator can edit his comment.
        /// </summary>
        public static string NotPermissionEditComment {
            get {
                return ResourceManager.GetString("NotPermissionEditComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No preview for this file.
        /// </summary>
        public static string NotPreview {
            get {
                return ResourceManager.GetString("NotPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Owner can&apos;t leave workspace.
        /// </summary>
        public static string OwnerCannotLeaveWorkspace {
            get {
                return ResourceManager.GetString("OwnerCannotLeaveWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is already created.
        /// </summary>
        public static string PasswordIsExist {
            get {
                return ResourceManager.GetString("PasswordIsExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You cannot send invite to your account.
        /// </summary>
        public static string SendInviteYourself {
            get {
                return ResourceManager.GetString("SendInviteYourself", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sprint is not in the workspace.
        /// </summary>
        public static string SprintIsNotInWorkspace {
            get {
                return ResourceManager.GetString("SprintIsNotInWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sprint not found.
        /// </summary>
        public static string SprintNotFound {
            get {
                return ResourceManager.GetString("SprintNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sprints already off.
        /// </summary>
        public static string SprintsAlreadyOff {
            get {
                return ResourceManager.GetString("SprintsAlreadyOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sprints already on.
        /// </summary>
        public static string SprintsAlreadyOn {
            get {
                return ResourceManager.GetString("SprintsAlreadyOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t add sprint, because it isn&apos;t used in this workspace.
        /// </summary>
        public static string SprintsNotOn {
            get {
                return ResourceManager.GetString("SprintsNotOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Task not found.
        /// </summary>
        public static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This status not exist.
        /// </summary>
        public static string TaskStatusNotFound {
            get {
                return ResourceManager.GetString("TaskStatusNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction failed.
        /// </summary>
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error has occured.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This user already accepted your invite.
        /// </summary>
        public static string UserAcceptedInvite {
            get {
                return ResourceManager.GetString("UserAcceptedInvite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This user has already assigned.
        /// </summary>
        public static string UserAlreadyAssigned {
            get {
                return ResourceManager.GetString("UserAlreadyAssigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User already has invite, wait for a answer.
        /// </summary>
        public static string UserAlreadyHasInvite {
            get {
                return ResourceManager.GetString("UserAlreadyHasInvite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User with this usernamre already exist.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t member of current workspace.
        /// </summary>
        public static string UserNotMember {
            get {
                return ResourceManager.GetString("UserNotMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workspace ot found.
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong code or this code is deprecated, try again!.
        /// </summary>
        public static string WrongResetPasswordCode {
            get {
                return ResourceManager.GetString("WrongResetPasswordCode", resourceCulture);
            }
        }
    }
}
